name: deploy
run-name: ${{ github.actor }} is deploying
on: [push]
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container:
      image: 726059925999.dkr.ecr.eu-west-2.amazonaws.com/catalyst-images:latest
      credentials:
        username: AWS
        password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - run: terraform -help