name: deploy
on: [push]
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    # permissions:
    #   id-token: write
    #   contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: arn:aws:iam::726059925999:role/github-role
      TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}
    # container:
    #   image: 726059925999.dkr.ecr.eu-west-2.amazonaws.com/catalyst-images:latest
    #   credentials:
    #     username: AWS
    #     password: ${{ secrets.ECR_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: terraform init
      - run: terraform fmt
      - run: terraform validate
      - run: terraform plan
      - run: terraform apply -auto-approve