name: destroy
on: [workflow_dispatch]
jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: arn:aws:iam::726059925999:role/github-role
      TF_HTTP_PASSWORD: ${{ secrets.TF_HTTP_PASSWORD }}
      GOOGLE_IDP_APP_ID: ${{ secrets.GOOGLE_IDP_APP_ID }}
      GOOGLE_IDP_APP_SECRET: ${{ secrets.GOOGLE_IDP_APP_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init
        run: terraform init

      - name: Destroy
        run: terraform destroy -auto-approve -var environment=dev -var google-app-id ${GOOGLE_IDP_APP_ID} -var google-app-secret ${GOOGLE_IDP_APP_SECRET}
